version: 2.1
orbs:
  node: circleci/node@2.1.0
jobs:
  docker-con:
    executor:
      name: node/default
    steps:
      - checkout
      - setup_remote_docker

  test_server:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
         app-dir: ./server
      - run:
         command: npm test
         working_directory: ./server

  test_client:
    executor: 
      name: node/default
    steps:
      - checkout
      - node/install-packages:
         app-dir: ./client
      - run:
         command: npm test
         working_directory: ./client

  dhub_pub:
    machine: true
    steps:
      - checkout
      - run:
         command: |
           echo "$PASS_DOCKHUB" | docker login -u "b0niu" --password-stdin
           sudo docker build ./server -t b0niu/server
           sudo docker push b0niu/server
      - run:
         command: |
           echo "$PASS_DOCKHUB" | docker login -u "b0niu" --password-stdin
           sudo docker build ./client -t b0niu/client
           sudo docker push b0niu/client

workflows:
    build-and-test:
      jobs:
       - docker-con
       - test_server
       - test_client
       - dhub_pub
