version: 2.1
orbs:
  node: circleci/node@2.1.0
jobs:
  docker-con:
    executor:
      name: node/default
    steps:
      - checkout
      - setup_remote_docker

  test_server:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
         app-dir: ./server
      - run:
         command: npm test
         working_directory: ./server

  test_client:
    executor: 
      name: node/default
    steps:
      - checkout
      - node/install-packages:
         app-dir: ./client
      - run:
         command: npm test
         working_directory: ./client

  dhub_pub:
    machine: true
    steps:
      - checkout
      - run:
         command: |
           echo "$PASS_DOCKHUB" | docker login -u "b0niu" --password-stdin
           sudo docker build ./server -t b0niu/serv
           sudo docker push b0niu/serv
      - run:
         command: |
           echo "$PASS_DOCKHUB" | docker login -u "b0niu" --password-stdin
           sudo docker build ./client -t b0niu/cli
           sudo docker push b0niu/cli

workflows:
    build-and-test:
      jobs:
<<<<<<< HEAD
       - docker-con:
           filters:
            branches:
              only:
                - master
       - test_server:
          filters:
            branches:
              only:
                - master
       - test_client:
          filters:
            branches:
              only:
                - master
       - dhub_pub:
          filters:
            branches:
              only:
                - master
=======
       - docker-con
       - test_server
       - test_client
       - dhub_pub:
>>>>>>> 44fce2a2a014caf1066fa6c8eb89035f31b92b63
          requires:
            - docker-con
            - test_server
            - test_client
